# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 23:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u4ea7\u54c1\u540d')),
                ('desc', models.CharField(max_length=300, verbose_name='\u4ea7\u54c1\u7b80\u4ecb')),
                ('detail', models.TextField(verbose_name='\u4ea7\u54c1\u8be6\u60c5')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='\u4ea7\u54c1\u56fe')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1',
                'verbose_name_plural': '\u4ea7\u54c1',
            },
        ),
    ]
