# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 18:40
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171101_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u4f01\u4e1a\u4ecb\u7ecd'),
        ),
    ]
