# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171115_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='detail',
            field=models.TextField(verbose_name='\u4ea7\u54c1\u8be6\u60c5'),
        ),
    ]
