# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='age',
        ),
    ]
