# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 18:40
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='companypost',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u4f01\u4e1a\u4ecb\u7ecd'),
        ),
    ]
