# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20171115_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='name',
            field=models.CharField(default='dadsa', max_length=20, verbose_name='\u4f01\u4e1a\u540d'),
            preserve_default=False,
        ),
    ]
